DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS avatar;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE avatar (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  body_height INTEGER NOT NULL,
  body_weight INTEGER NOT NULL,
  skin_tone TEXT NOT NULL,
  sex TEXT NOT NULL,
  FOREIGN KEY (owner_id) REFERENCES user (id)
);